// actionTypes.js
export const FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS";
export const FETCH_PEOPLE_FAILURE = "FETCH_PEOPLE_FAILURE";

export const FETCH_PERSON_DETAILS_SUCCESS = "FETCH_PERSON_DETAILS_SUCCESS";
export const FETCH_PERSON_DETAILS_FAILURE = "FETCH_PERSON_DETAILS_FAILURE";

export const RESET_PERSON_DETAILS = "RESET_PERSON_DETAILS";

export const FETCH_HOMEWORLD_SUCCESS = "FETCH_HOMEWORLD_SUCCESS";
export const FETCH_HOMEWORLD_FAILURE = "FETCH_HOMEWORLD_FAILURE";

export const FETCH_SPECIES_SUCCESS = "FETCH_SPECIES_SUCCESS";
export const FETCH_SPECIES_FAILURE = "FETCH_SPECIES_FAILURE";

export const FETCH_STARSHIPS_SUCCESS = "FETCH_STARSHIPS_SUCCESS";
export const FETCH_STARSHIPS_FAILURE = "FETCH_STARSHIPS_FAILURE";

export const FETCH_FILMS_SUCCESS = "FETCH_FILMS_SUCCESS";
export const FETCH_FILMS_FAILURE = "FETCH_FILMS_FAILURE";

